### ISSUE TITLE
Basset is expecting the wrong path on prod (ubuntu)

### ISSUE THREAD

**Issue by sidis405** [Laravel-Backpack/basset#88]
Hi folks

a bit of a headscratcher here.

I've been using Backpack for years and this is the first time i'm using 6.x.

I have this application locally (mac), where backpack is working and rendering fine.

Just deployed a few hours ago to an Ubuntu vps. Application installs fine, Backpack runs fins as far as functionalities go, but 0m having a problem with assets.

I'm using the CoreUIV4.

Only in **production** the css for coreUI is not being picked up.
The path it is looking for is in the **laravel vendor dir**

```
https://[redacted].com/var/www/[redacted].com/vendor/backpack/theme-coreuiv4/resources/assets/css/coreui4.css?3af67d0533b0
```

while what it needs is perfectly placed in storage/app/public/basset.

Matter of fact locally it is still working as it is needed.

```
https://local-version.test/storage/basset/vendor/backpack/theme-coreuiv4/resources/assets/css/coreui4.css?0355d650212d
````

Am I missing something obvious?

Thank you kindly in advance

[Edit]

Forgot to mention that the storage symlink is present and basset:install runs without problems

![Screenshot 2023-08-25 at 16 23 04](https://github.com/Laravel-Backpack/basset/assets/844961/0aaf26c4-3fb1-46a9-8abe-0995240ac5e4)

**Comment by pxpm** [comment]
Hey @sidis405 thanks for the well writen report 🙏 

Does `php artisan basset:check` output any error in the production environment ? 

Cheers

**Comment by sidis405** [comment]
Hi @pxpm thank you for the prompt response :)

![Screenshot 2023-08-25 at 16 34 21](https://github.com/Laravel-Backpack/basset/assets/844961/4e076442-ec5e-4119-881e-ff2f79629bb5)

Nope `php artisan basset:check` runs without any issues.

I've tried the majority of things i could think of (including, naively but worth a try) bringing in all the basset content from my local env, but to no result.

Fact is as i said this is the first time i'm using basset so i'm not quite sure of the internals and why it would try to resolve from the vendor folder (correctly i might add because vendor/backpack/theme-coreuiv4/resources/assets/css/coreui4.css does in fact exist in vendor)

**Comment by pxpm** [comment]
No problem, glad to help. Does the disk used in basset have the same configs locally and in prod ? 

What if you set the basset disk to `basset` in `config/backpack/basset.php` (if you don't have that file you can publish it with: `php artisan vendor:publish --provider="Backpack\Basset\BassetServiceProvider"` ) and after changing the config do a `php artisan config:clear && php artisan basset:clear && php artisan basset:cache`

Let me know how it goes. 

Cheers

**Comment by pxpm** [comment]
> ![Screenshot 2023-08-25 at 16 39 24](https://user-images.githubusercontent.com/844961/263301439-bbf43447-34ef-485d-a037-5e40b3289f60.png)
> 
> So the piece i suspect i'm missing is making basset aware that the assets are in storage. I don't recall frankly doing anything particular with this locally (but i might be drawing a blank).

This usually happen when the symlink is not properly created. It may be giving a false positive that it exists, but in fact it does not.

**Comment by sidis405** [comment]
I'll catch up on both replies together:

The disk i've left to the default one, `public`, so there was no initial need to publish and use the config file.

Non the less, i published it.
I can check from tinker that the value of `config('backpack.basset.disk')` is in fact `public`.

`php artisan config:clear && php artisan basset:clear && php artisan basset:cache` runs successfully with no issues.
The files are in fact in place `public/storage/basset/vendor/backpack/theme-coreuiv4/resources/assets/css/coreui4.css` and `public/storage/basset/vendor/backpack/crud/src/resources/assets/css/common.css` .

As far as the symlink being properly set, I can reach them from the browser respectively at `https://[redacted].com/storage/basset/vendor/backpack/crud/src/resources/assets/css/common.css` and `https://[redacted].com/storage/basset/vendor/backpack/theme-coreuiv4/resources/assets/css/coreui4.css`
which is the exact path where they should be (and are on the local version)

**Comment by sidis405** [comment]
Let me quickly add to the wth effect.

If i run `basset:clear` with nothing else:

I can see the login path i styled properly
![Screenshot 2023-08-25 at 17 00 42](https://github.com/Laravel-Backpack/basset/assets/844961/621a0676-d98d-46eb-8a9b-ae316f066896)

Once i log in the Dash (or any other pages) remain unstyled

![Screenshot 2023-08-25 at 17 03 15](https://github.com/Laravel-Backpack/basset/assets/844961/208bbe22-6e9d-46b4-ba5b-4b393d16e836)

BUT, and here's the kicker: the asset references in the html head are correct, but don't seem to be applied at all

![Screenshot 2023-08-25 at 17 02 23](https://github.com/Laravel-Backpack/basset/assets/844961/78fc2564-0a60-4642-8658-613e70359ed5)

**Comment by sidis405** [comment]
The dashboard think was a fluke. It depends on the environment, which i changed. Nothing there, my bad.

Here is the output of `basset:cache`
![Screenshot 2023-08-25 at 17 37 42](https://github.com/Laravel-Backpack/basset/assets/844961/1b25a59b-e5cc-4491-9b31-2cde09ac0e54)

On the console (and network, contextually), in all cases are only the 404 of the static assets it can't find.

**Comment by sidis405** [comment]
Oh i see my bad. Here it is below run together with `config:clear` and `basset:clear`

![Screenshot 2023-08-25 at 17 42 00](https://github.com/Laravel-Backpack/basset/assets/844961/930ebded-c58f-423c-8db4-eab5417394cc)

**Comment by sidis405** [comment]
How does `backpack` resolve those assets in the header? Is there a cache/autoload file that is generated and that i can inspect?

**Comment by pxpm** [comment]
There shoud be a .basset file inside `public/storage/basset` folder . 

Can  you see it ?

**Comment by sidis405** [comment]
Yep i do. Here's what's in it

```
{
    "https://github.com/adobe-fonts/source-sans/releases/download/3.046R/WOFF2-source-sans-3.046R.zip": "/1",
    "https://github.com/tinymce/tinymce-dist/archive/refs/tags/6.3.2.tar.gz": "/1",
    "vendor/backpack/crud/src/resources/assets/css/common.css": "/vendor/backpack/crud/src/resources/assets/css/common.css",
    "vendor/backpack/crud/src/resources/assets/img/spinner.svg": "/vendor/backpack/crud/src/resources/assets/img/spinner.svg",
    "vendor/backpack/crud/src/resources/assets/js/common.js": "/vendor/backpack/crud/src/resources/assets/js/common.js",
    "vendor/backpack/crud/src/resources/assets/libs/jquery.mjs.nestedSortable2.js": "/vendor/backpack/crud/src/resources/assets/libs/jquery.mjs.nestedSortable2.js",
    "vendor/backpack/pro/resources/assets/js/icon-picker.js": "/vendor/backpack/pro/resources/assets/js/icon-picker.js",
    "vendor/backpack/theme-coreuiv2/resources/assets/css/coreuiv2.css": "/vendor/backpack/theme-coreuiv2/resources/assets/css/coreuiv2.css",
    "vendor/backpack/theme-coreuiv4/resources/assets/css/coreui4.css": "/vendor/backpack/theme-coreuiv4/resources/assets/css/coreui4.css",
    "vendor/backpack/theme-tabler/resources/assets/css/style.css": "/vendor/backpack/theme-tabler/resources/assets/css/style.css",
    "vendor/backpack/theme-tabler/resources/assets/js/tabler.js": "/vendor/backpack/theme-tabler/resources/assets/js/tabler.js"
}
```

**but this is identical to my local setup.**

So i guess these key-value pairs get interpreted and used as a map.
The question now becomes in a case like 
```
"vendor/backpack/crud/src/resources/assets/css/common.css": "/vendor/backpack/crud/src/resources/assets/css/common.css"
```

how does it once get correctly translated to `storage/basset/vendor/backpack/crud/src/resources/assets/css/common.css` and then another times stay `vendor/backpack/crud/src/resources/assets/css/common.css`?

**Comment by sidis405** [comment]
> **but this is identical to my local setup.**

There's definitely something not right with this though. Not sure it should be like this even locally. I think locally it might be relating to cached views

**Comment by sidis405** [comment]
> > **but this is identical to my local setup.**
> 
> There's definitely something not right with this though. Not sure it should be like this even locally. I think locally it might be relating to cached views

Anyhow, i'm doing some reverse engineering here not knowing my way around, and i can get down the rabbit hole to BassetManager. I can see that the url it produces is actually correct (on the basset() method).

Would you be able to point out any bits i might be missing here?
In the sense that, basset is identifying the bits correctly but on the page they end up with their absolute path

**Comment by sidis405** [comment]
@pxpm  So made some progress with this.

Clearing out with `basset:clear` and changing the theme to CoreUI2 or Tabler, works.
Not caching though. If i cache with `basset:cache` i start getting these weird 419 errors.

I'd be happy to help reproduce and debug this if you want

**Comment by pxpm** [comment]
Thanks @sidis405 that's definatelly something worth investigating . 

I am not sure if tomorrow I will have time, but I think sunday, or atmost monday I can get an ubunto vps to test this. 

If in the meanwhile you get something new, please share it with me. 

I will let you know my findings, and we will try to get to the bottom of this. 

Thanks for the preserverance and sorry for the bad experience 🙏 

Cheers

**Comment by sidis405** [comment]
@pxpm Absolutely and don't worry about it. It's part of the job :)

**Comment by tabacitu** [comment]
> I am not sure if tomorrow I will have time, but I think sunday, or atmost monday I can get an ubuntu vps to test this.

@pxpm , I don't think the problem here is the Ubuntu VPS. https://demo.backpackforlaravel.com/ is running Ubuntu 20.04.2 LTS and Basset is working fine there. I'm on a Mac, runs fine there. You're on Windows, runs fine there.

> What if you set the basset disk to basset in `config/backpack/basset.php` (if you don't have that file you can publish it with: `php artisan vendor:publish --provider="Backpack\Basset\BassetServiceProvider"`) and after changing the config do a `php artisan config:clear && php artisan basset:clear && php artisan basset:cache`

This is what I would recommend too - changing the basset disk to be `basset` instead of `public`. Because it seems to me like the public disk configuration might be the problem here... the files get saved to all the right places... but the output URL is wrong...

So @sidis405 let's try this:

1. Can you please change the disk to `basset` - should work both in local and public. Alternatively, if you cannot do that, can you please tell us the configuration of your `public` disk? The array config in `config/storage.php`
2. Tell us something - is this a fresh Laravel app... or an older app that you've upgraded, Laravel, Backpack everything?

We can do this 💪

**Comment by promatik** [comment]
Hey! Sorry for coming late to the party, I'll just support tabacitu comment, by saying that my guess is also to a miss configuration of the public disk, so changing it to `basset` should work.

I'm guessing this is an old project being upgraded, and the `url` is not correctly set on the public disk.

By the way @sidis405, do it by going adding `BASSET_DISK=basset` to the .env file 👌

**Comment by sidis405** [comment]
Hi @tabacitu and @promatik 

I'll try this right away.

As far as the project goes, this is brand new. Started about a month ago so the first install was Backpack 6.x. This was not an upgrade or something. 

Non the less, will try the disk thing right away and bring back some (hopefully useful) feedback.

**Comment by sidis405** [comment]
Ok, so:

- i set BASSET_DISK=basset
-

**Comment by sidis405** [comment]
[Closed this by mistake]

Ok, so:

- i set `BASSET_DISK=basset`
- set theme to `CoreUI4` which is the one causing problems as per my previous message
- ran `php artisan config:clear && php artisan basset:clear && php artisan basset:cache`


The `realpath` references in the head section are gone.


![Screenshot 2023-08-28 at 10 55 35](https://github.com/Laravel-Backpack/basset/assets/844961/c61f0f77-5077-42b6-9434-c513d51e72f7)


What actually does remain, and this i can verify also locally by setting the UI theme to `CoreUI4` is the following:

![Screenshot 2023-08-28 at 10 55 46](https://github.com/Laravel-Backpack/basset/assets/844961/95bfb156-fdfd-489a-980f-4fda0478f501)

No errors in the console and all items required in the head section (or elsewhere) are all correctly fetched by the browser

**Comment by Astriel** [comment]
Everything was working fine the first time I've built everything. But after switching branch, and updating everything with composer, I'm coming back to get that broken design with no solution on my side I guess. 

- Screens are still there
- Login screen is working fine
- public disk is correctly setup
- I can have access to the basset files from the browser
- No error in the console
- The only error I got is when I'm launching php artisan basset:check

```php artisan basset:check

   INFO  Checking Backpack Basset installation.

  Initializing basset check ................................................................................................................... DONE
  Checking cache storage ...................................................................................................................... DONE
  Fetching a basset .......................................................................................................................... ERROR

   ERROR  cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://myproject.local/storage/basset/vendor/backpack/basset/tests/Helpers/basset-test.js.
```

But if I try to access the test file in my browser, it's working fine as well.

Thanks for the tip, I'll try also to switch on the other UI to be able to progress !

**Comment by Astriel** [comment]
@sidis405 I can confirm everything is working now with the V2 of the UI. Sounds like something is broken on the V4 of the UI ?

**Comment by sidis405** [comment]
Yep that seems reasonable.
Haven’t really had more time to look into it though.

**Comment by sidis405** [comment]
Hi folks

i can see this has moved along a bit towards [https://github.com/Laravel-Backpack/theme-coreuiv4/issues/50](https://github.com/Laravel-Backpack/theme-coreuiv4/issues/50). [https://github.com/Laravel-Backpack/theme-coreuiv4/issues/50](https://github.com/Laravel-Backpack/theme-coreuiv4/issues/50) and eventually [https://github.com/Laravel-Backpack/basset/issues/95](https://github.com/Laravel-Backpack/basset/issues/95)

Is there a patch/update expected for this?

Non the less, the issue referenced here, is not in a local env with a development purpose self-signed cert.
It's a DO VPS with a Let's Encrypt cert.

**Comment by tabacitu** [comment]
@sidis405 this issue should be fixed by https://github.com/Laravel-Backpack/basset/pull/96 - you'd have to set `'verify_ssl_certificate' => false` in your config file and it should work. I'm going to ping Pedro to speed up the merge, thanks for the reminder 🙏

**Comment by sidis405** [comment]
Hi @tabacitu thank you for the prompt reply. I'll pull in shortly that PR and check it out and then wait for the merge :) thanks again

**Comment by Astriel** [comment]
Hey there ! 
I've tried it on my side @sidis405 and sounds like basset is working well now, but on my side, still the same UI problem as you were facing.

**Comment by sidis405** [comment]
I apologise for the delay.

@tabacitu i saw that it was merged, updated, nuked all the basset caches/configs. Nada.
And then i removed the local theme-coreui4.php file i had published in my config.
Worked like a charm, already in the prod server.

@Astriel remove any specific theme config you might have like config/theme-coreui4.php, clear basset and cache again. Should work with no issues

**Comment by Astriel** [comment]
Indeed, I had to delete the config/theme-coreui4.php and clear all the cache, now everything is working fine. Thanks for the advice !

**Comment by pxpm** [comment]
Hey guys, can any of you publish the contents of your config files?
Thanks

**Comment by Astriel** [comment]
For now, it's working while the file is deleted. I'm going to publish it again to check the content and send it to you.

**Comment by sidis405** [comment]
Here is the `theme-coreui4.php` file that was giving troubles.

In hindsight, that `sidebar-pills` class might've been the culprit

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Theme Configuration Values
    |--------------------------------------------------------------------------
    |
    | The file provides extra configs on top of config/backpack/ui.php
    |
    | Any value set here will override the ones defined in
    | config/backpack/ui.php when this theme is in use.
    |
    */

    // the layout used for authenticated users in the application
    // this layout is used to display errors to logged users
    'layout' => 'top_left',

    // -------
    // CLASSES
    // -------

    // These can help make the admin panel look similar to your project's design.
    'classes' => [

        'header' => 'app-header bg-light border-0 navbar',
        // For background colors use: bg-dark, bg-primary, bg-secondary, bg-danger, bg-warning, bg-success, bg-info, bg-blue, bg-light-blue, bg-indigo, bg-purple, bg-pink, bg-red, bg-orange, bg-yellow, bg-green, bg-teal, bg-cyan, bg-white
        // For links to be visible on different background colors use: "navbar-dark", "navbar-light", "navbar-color"

        'body' => 'app aside-menu-fixed sidebar-lg-show',
        // Try sidebar-hidden, sidebar-fixed, sidebar-compact, sidebar-lg-show

        'sidebar' => 'sidebar sidebar-pills bg-light',
        // Remove "sidebar-transparent" for standard sidebar look
        // Try "sidebar-light" or "sidebar-dark" for dark/light links
        // You can also add a background class like bg-dark, bg-primary, bg-secondary, bg-danger, bg-warning, bg-success, bg-info, bg-blue, bg-light-blue, bg-indigo, bg-purple, bg-pink, bg-red, bg-orange, bg-yellow, bg-green, bg-teal, bg-cyan

        'footer' => 'app-footer d-print-none',
        // hide it with d-none
        // change background color with bg-dark, bg-primary, bg-secondary, bg-danger, bg-warning, bg-success, bg-info, bg-blue, bg-light-blue, bg-indigo, bg-purple, bg-pink, bg-red, bg-orange, bg-yellow, bg-green, bg-teal, bg-cyan, bg-white

        'tableWrapper' => null,
        'table' => null,
    ],

];
```
